package com.huy.enterprise.ai.inventory;

import com.huy.enterprise.alert.Alert;
import com.huy.enterprise.alert.AlertRepository;
import com.huy.enterprise.common.enums.AlertPriority;
import com.huy.enterprise.common.enums.AlertStatus;
import com.huy.enterprise.common.enums.ImpactLevel;
import com.huy.enterprise.common.enums.RiskEventSource;
import com.huy.enterprise.common.enums.RiskEventStatus;
import com.huy.enterprise.common.enums.RiskType;
import com.huy.enterprise.monitoring.RiskRuleCode;
import com.huy.enterprise.product.ProductRepository;
import com.huy.enterprise.risk.RiskEvent;
import com.huy.enterprise.risk.RiskEventRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class PredictiveInventoryRiskService {
    private static final List<RiskEventStatus> ACTIVE_RISK_STATUSES =
            List.of(RiskEventStatus.OPEN, RiskEventStatus.INVESTIGATING);
    private static final List<AlertStatus> ACTIVE_ALERT_STATUSES =
            List.of(AlertStatus.NEW, AlertStatus.READ);

    private final InventoryForecastService forecasts;
    private final ProductRepository products;
    private final RiskEventRepository riskEvents;
    private final AlertRepository alerts;

    @Transactional
    public InventoryForecastResponse refresh(UUID productId) {
        InventoryForecastResponse forecast = forecasts.forecast(productId);
        String sourceRef = "AI_STOCKOUT:" + productId + ":28D";
        RiskEvent existing = riskEvents
                .findFirstByAutoGeneratedTrueAndRuleCodeAndSourceRefAndStatusIn(
                        RiskRuleCode.AI_STOCKOUT_FORECAST, sourceRef, ACTIVE_RISK_STATUSES)
                .orElse(null);

        if (forecast.stockoutRisk() != ImpactLevel.HIGH && forecast.stockoutRisk() != ImpactLevel.CRITICAL) {
            if (existing != null) {
                resolve(existing);
            }
            return forecast;
        }

        RiskEvent risk = existing == null ? new RiskEvent() : existing;
        risk.setSource(RiskEventSource.AI_FORECAST);
        risk.setAutoGenerated(true);
        risk.setRuleCode(RiskRuleCode.AI_STOCKOUT_FORECAST);
        risk.setSourceRef(sourceRef);
        risk.setRiskType(RiskType.INVENTORY);
        risk.setImpactLevel(forecast.stockoutRisk());
        risk.setStatus(existing == null ? RiskEventStatus.OPEN : risk.getStatus());
        risk.setDetectedAt(existing == null ? OffsetDateTime.now() : risk.getDetectedAt());
        risk.setProduct(products.getReferenceById(productId));
        risk.setTitle("AI stockout forecast - " + forecast.productCode());
        risk.setDescription(buildDescription(forecast));
        risk = riskEvents.save(risk);
        ensureAlert(risk);
        return forecast;
    }

    private String buildDescription(InventoryForecastResponse forecast) {
        return "AI forecast predicts " + forecast.stockoutRisk() + " inventory risk for product "
                + forecast.productCode() + ". Current inventory=" + forecast.currentInventory()
                + ", forecast demand 28d=" + forecast.forecastDemand().next28Days()
                + ", incoming supply 28d=" + forecast.incomingSupply().next28Days()
                + ", projected inventory 28d=" + forecast.projectedInventory().next28Days()
                + (forecast.projectedStockoutDate() == null
                ? "."
                : ", projected stockout date=" + forecast.projectedStockoutDate() + ".");
    }

    private void ensureAlert(RiskEvent risk) {
        Alert alert = alerts.findFirstByRiskEventIdAndStatusIn(risk.getId(), ACTIVE_ALERT_STATUSES).orElse(null);
        if (alert == null) {
            alert = new Alert();
            alert.setRiskEvent(risk);
            alert.setStatus(AlertStatus.NEW);
        }
        alert.setAlertType(RiskRuleCode.AI_STOCKOUT_FORECAST.name());
        alert.setTitle(risk.getTitle());
        alert.setMessage(risk.getDescription());
        alert.setPriority(AlertPriority.valueOf(risk.getImpactLevel().name()));
        alerts.save(alert);
    }

    private void resolve(RiskEvent risk) {
        risk.setStatus(RiskEventStatus.RESOLVED);
        riskEvents.save(risk);
        OffsetDateTime resolvedAt = OffsetDateTime.now();
        for (Alert alert : alerts.findByRiskEventIdAndStatusIn(risk.getId(), ACTIVE_ALERT_STATUSES)) {
            alert.setStatus(AlertStatus.RESOLVED);
            alert.setResolvedAt(resolvedAt);
            alerts.save(alert);
        }
    }
}
