package com.huy.enterprise.monitoring;

import com.huy.enterprise.alert.Alert;
import com.huy.enterprise.alert.AlertRepository;
import com.huy.enterprise.common.enums.AlertStatus;
import com.huy.enterprise.common.enums.ImpactLevel;
import com.huy.enterprise.inventory.InventoryItem;
import com.huy.enterprise.inventory.InventoryItemRepository;
import com.huy.enterprise.inventory.Warehouse;
import com.huy.enterprise.order.PurchaseOrderRepository;
import com.huy.enterprise.product.Product;
import com.huy.enterprise.risk.RiskEvent;
import com.huy.enterprise.risk.RiskEventRepository;
import com.huy.enterprise.shipment.ShipmentRepository;
import com.huy.enterprise.supplier.SupplierRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicReference;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class RiskMonitoringServiceTest {
    @Mock InventoryItemRepository inventoryItems;
    @Mock PurchaseOrderRepository purchaseOrders;
    @Mock ShipmentRepository shipments;
    @Mock SupplierRepository suppliers;
    @Mock RiskEventRepository riskEvents;
    @Mock AlertRepository alerts;

    @InjectMocks RiskMonitoringService service;

    @Test
    void lowStockImpactMatchesBusinessRules() {
        assertThat(RiskMonitoringService.lowStockImpact(new BigDecimal("100"), new BigDecimal("20")))
                .isEqualTo(ImpactLevel.MEDIUM);
        assertThat(RiskMonitoringService.lowStockImpact(new BigDecimal("20"), new BigDecimal("20")))
                .isEqualTo(ImpactLevel.MEDIUM);
        assertThat(RiskMonitoringService.lowStockImpact(new BigDecimal("5"), new BigDecimal("20")))
                .isEqualTo(ImpactLevel.HIGH);
        assertThat(RiskMonitoringService.lowStockImpact(BigDecimal.ZERO, new BigDecimal("20")))
                .isEqualTo(ImpactLevel.CRITICAL);
        assertThat(RiskMonitoringService.lowStockImpact(BigDecimal.ZERO, BigDecimal.ZERO))
                .isEqualTo(ImpactLevel.CRITICAL);
    }

    @Test
    void delayImpactMatchesBusinessRules() {
        assertThat(RiskMonitoringService.delayImpact(1, 3, 7)).isEqualTo(ImpactLevel.MEDIUM);
        assertThat(RiskMonitoringService.delayImpact(2, 3, 7)).isEqualTo(ImpactLevel.MEDIUM);
        assertThat(RiskMonitoringService.delayImpact(3, 3, 7)).isEqualTo(ImpactLevel.HIGH);
        assertThat(RiskMonitoringService.delayImpact(7, 3, 7)).isEqualTo(ImpactLevel.HIGH);
        assertThat(RiskMonitoringService.delayImpact(8, 3, 7)).isEqualTo(ImpactLevel.CRITICAL);
    }

    @Test
    void repeatedLowStockScanDoesNotCreateDuplicateRiskOrAlert() {
        InventoryItem item = lowStockItem(new BigDecimal("5"), new BigDecimal("20"));
        AtomicReference<RiskEvent> storedRisk = new AtomicReference<>();
        AtomicReference<Alert> storedAlert = new AtomicReference<>();

        when(inventoryItems.findLowStockItems()).thenReturn(List.of(item));
        when(purchaseOrders.findOverdueOrders(any(), anyList())).thenReturn(List.of());
        when(shipments.findOverdueShipments(any(), anyList())).thenReturn(List.of());
        when(suppliers.findByRiskLevel(any())).thenReturn(List.of());
        when(riskEvents.findFirstByAutoGeneratedTrueAndRuleCodeAndSourceRefAndStatusIn(any(), any(), anyList()))
                .thenAnswer(inv -> Optional.ofNullable(storedRisk.get()));
        when(riskEvents.save(any(RiskEvent.class))).thenAnswer(inv -> {
            RiskEvent risk = inv.getArgument(0);
            if (risk.getId() == null) risk.setId(UUID.randomUUID());
            storedRisk.set(risk);
            return risk;
        });
        when(riskEvents.findByAutoGeneratedTrueAndRuleCodeAndStatusIn(any(), anyList()))
                .thenAnswer(inv -> storedRisk.get() == null ? List.of() : List.of(storedRisk.get()));
        when(alerts.findFirstByRiskEventIdAndStatusIn(any(), anyList()))
                .thenAnswer(inv -> Optional.ofNullable(storedAlert.get()));
        when(alerts.save(any(Alert.class))).thenAnswer(inv -> {
            Alert alert = inv.getArgument(0);
            if (alert.getId() == null) alert.setId(UUID.randomUUID());
            storedAlert.set(alert);
            return alert;
        });

        RiskMonitoringResult first = service.runMonitoring();
        RiskMonitoringResult second = service.runMonitoring();

        assertThat(first.getRiskEventsCreated()).isEqualTo(1);
        assertThat(first.getAlertsCreated()).isEqualTo(1);
        assertThat(second.getRiskEventsCreated()).isZero();
        assertThat(second.getAlertsCreated()).isZero();
        assertThat(storedRisk.get().getRuleCode()).isEqualTo(RiskRuleCode.LOW_STOCK);
        assertThat(storedRisk.get().isAutoGenerated()).isTrue();
    }

    @Test
    void automaticLowStockRiskAndAlertAreResolvedWhenConditionClears() {
        InventoryItem item = lowStockItem(new BigDecimal("5"), new BigDecimal("20"));
        AtomicReference<RiskEvent> storedRisk = new AtomicReference<>();
        AtomicReference<Alert> storedAlert = new AtomicReference<>();

        when(inventoryItems.findLowStockItems()).thenReturn(List.of(item), List.of());
        when(purchaseOrders.findOverdueOrders(any(), anyList())).thenReturn(List.of());
        when(shipments.findOverdueShipments(any(), anyList())).thenReturn(List.of());
        when(suppliers.findByRiskLevel(any())).thenReturn(List.of());
        when(riskEvents.findFirstByAutoGeneratedTrueAndRuleCodeAndSourceRefAndStatusIn(any(), any(), anyList()))
                .thenAnswer(inv -> Optional.ofNullable(storedRisk.get()));
        when(riskEvents.save(any(RiskEvent.class))).thenAnswer(inv -> {
            RiskEvent risk = inv.getArgument(0);
            if (risk.getId() == null) risk.setId(UUID.randomUUID());
            storedRisk.set(risk);
            return risk;
        });
        when(riskEvents.findByAutoGeneratedTrueAndRuleCodeAndStatusIn(any(), anyList()))
                .thenAnswer(inv -> storedRisk.get() == null ? List.of() : List.of(storedRisk.get()));
        when(alerts.findFirstByRiskEventIdAndStatusIn(any(), anyList())).thenReturn(Optional.empty());
        when(alerts.save(any(Alert.class))).thenAnswer(inv -> {
            Alert alert = inv.getArgument(0);
            if (alert.getId() == null) alert.setId(UUID.randomUUID());
            storedAlert.set(alert);
            return alert;
        });
        when(alerts.findByRiskEventIdAndStatusIn(any(), anyList()))
                .thenAnswer(inv -> storedAlert.get() == null || storedAlert.get().getStatus() == AlertStatus.RESOLVED
                        ? List.of() : List.of(storedAlert.get()));

        service.runMonitoring();
        RiskMonitoringResult resolved = service.runMonitoring();

        assertThat(storedRisk.get().getStatus().name()).isEqualTo("RESOLVED");
        assertThat(storedAlert.get().getStatus()).isEqualTo(AlertStatus.RESOLVED);
        assertThat(storedAlert.get().getResolvedAt()).isNotNull();
        assertThat(resolved.getRiskEventsResolved()).isEqualTo(1);
        assertThat(resolved.getAlertsResolved()).isEqualTo(1);
    }

    private InventoryItem lowStockItem(BigDecimal quantity, BigDecimal threshold) {
        Product product = new Product();
        product.setId(UUID.randomUUID());
        product.setProductCode("SP001");
        product.setName("Demo product");

        Warehouse warehouse = new Warehouse();
        warehouse.setId(UUID.randomUUID());
        warehouse.setWarehouseCode("WH01");
        warehouse.setName("Main warehouse");

        InventoryItem item = new InventoryItem();
        item.setId(UUID.randomUUID());
        item.setProduct(product);
        item.setWarehouse(warehouse);
        item.setQuantity(quantity);
        item.setLowStockThreshold(threshold);
        return item;
    }
}
