package com.huy.enterprise.monitoring;

import com.huy.enterprise.alert.Alert;
import com.huy.enterprise.alert.AlertRepository;
import com.huy.enterprise.common.enums.AlertPriority;
import com.huy.enterprise.common.enums.AlertStatus;
import com.huy.enterprise.common.enums.ImpactLevel;
import com.huy.enterprise.common.enums.PurchaseOrderStatus;
import com.huy.enterprise.common.enums.RiskEventSource;
import com.huy.enterprise.common.enums.RiskEventStatus;
import com.huy.enterprise.common.enums.RiskLevel;
import com.huy.enterprise.common.enums.RiskType;
import com.huy.enterprise.common.enums.ShipmentStatus;
import com.huy.enterprise.inventory.InventoryItem;
import com.huy.enterprise.inventory.InventoryItemRepository;
import com.huy.enterprise.order.PurchaseOrder;
import com.huy.enterprise.order.PurchaseOrderRepository;
import com.huy.enterprise.risk.RiskEvent;
import com.huy.enterprise.risk.RiskEventRepository;
import com.huy.enterprise.shipment.Shipment;
import com.huy.enterprise.shipment.ShipmentRepository;
import com.huy.enterprise.supplier.Supplier;
import com.huy.enterprise.supplier.SupplierRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.temporal.ChronoUnit;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.function.Consumer;

@Service
@RequiredArgsConstructor
public class RiskMonitoringService {
    private static final List<RiskEventStatus> ACTIVE_RISK_STATUSES =
            List.of(RiskEventStatus.OPEN, RiskEventStatus.INVESTIGATING);
    private static final List<AlertStatus> ACTIVE_ALERT_STATUSES =
            List.of(AlertStatus.NEW, AlertStatus.READ);
    private static final List<PurchaseOrderStatus> MONITORED_ORDER_STATUSES =
            List.of(PurchaseOrderStatus.ORDERED, PurchaseOrderStatus.IN_TRANSIT, PurchaseOrderStatus.DELAYED);
    private static final List<ShipmentStatus> MONITORED_SHIPMENT_STATUSES =
            List.of(ShipmentStatus.PENDING, ShipmentStatus.SHIPPING, ShipmentStatus.DELAYED);

    private final InventoryItemRepository inventoryItems;
    private final PurchaseOrderRepository purchaseOrders;
    private final ShipmentRepository shipments;
    private final SupplierRepository suppliers;
    private final RiskEventRepository riskEvents;
    private final AlertRepository alerts;

    @Value("${app.risk-monitoring.enabled:true}")
    private boolean enabled;

    @Value("${app.risk-monitoring.delayed-order.high-after-days:3}")
    private int orderHighAfterDays;

    @Value("${app.risk-monitoring.delayed-order.critical-after-days:7}")
    private int orderCriticalAfterDays;

    @Value("${app.risk-monitoring.delayed-shipment.high-after-days:3}")
    private int shipmentHighAfterDays;

    @Value("${app.risk-monitoring.delayed-shipment.critical-after-days:7}")
    private int shipmentCriticalAfterDays;

    private volatile OffsetDateTime lastScan;

    @Transactional
    public synchronized RiskMonitoringResult runMonitoring() {
        RiskMonitoringResult result = new RiskMonitoringResult();
        LocalDate today = LocalDate.now();

        checkLowStock(result);
        checkDelayedPurchaseOrders(today, result);
        checkDelayedShipments(today, result);
        checkHighRiskSuppliers(result);

        lastScan = result.getEvaluatedAt();
        return result;
    }

    @Transactional(readOnly = true)
    public RiskMonitoringSummary summary() {
        List<RiskEvent> active = riskEvents.findByAutoGeneratedTrueAndStatusIn(ACTIVE_RISK_STATUSES);
        return new RiskMonitoringSummary(
                enabled,
                lastScan,
                active.size(),
                active.stream().filter(r -> r.getImpactLevel() == ImpactLevel.CRITICAL).count(),
                active.stream().filter(r -> r.getImpactLevel() == ImpactLevel.HIGH).count(),
                active.stream().filter(r -> r.getRuleCode() == RiskRuleCode.LOW_STOCK).count(),
                active.stream().filter(r -> r.getRuleCode() == RiskRuleCode.DELAYED_PURCHASE_ORDER).count(),
                active.stream().filter(r -> r.getRuleCode() == RiskRuleCode.DELAYED_SHIPMENT).count(),
                active.stream().filter(r -> r.getRuleCode() == RiskRuleCode.HIGH_RISK_SUPPLIER).count());
    }

    private void checkLowStock(RiskMonitoringResult result) {
        Set<String> activeRefs = new HashSet<>();
        for (InventoryItem item : inventoryItems.findLowStockItems()) {
            String sourceRef = item.getId().toString();
            activeRefs.add(sourceRef);
            result.lowStockDetected();

            ImpactLevel impact = lowStockImpact(item.getQuantity(), item.getLowStockThreshold());
            String title = "Low stock detected - " + item.getProduct().getProductCode();
            String description = "Product " + item.getProduct().getProductCode()
                    + " at Warehouse " + item.getWarehouse().getWarehouseCode()
                    + " has quantity " + item.getQuantity()
                    + " while low stock threshold is " + item.getLowStockThreshold() + ".";

            ensureRisk(
                    RiskRuleCode.LOW_STOCK,
                    sourceRef,
                    RiskType.INVENTORY,
                    impact,
                    title,
                    description,
                    risk -> risk.setProduct(item.getProduct()),
                    result);
        }
        resolveMissing(RiskRuleCode.LOW_STOCK, activeRefs, result);
    }

    private void checkDelayedPurchaseOrders(LocalDate today, RiskMonitoringResult result) {
        Set<String> activeRefs = new HashSet<>();
        for (PurchaseOrder order : purchaseOrders.findOverdueOrders(today, MONITORED_ORDER_STATUSES)) {
            String sourceRef = order.getId().toString();
            activeRefs.add(sourceRef);
            result.delayedPurchaseOrderDetected();

            long daysLate = ChronoUnit.DAYS.between(order.getExpectedDeliveryDate(), today);
            ImpactLevel impact = delayImpact(daysLate, orderHighAfterDays, orderCriticalAfterDays);
            if (order.getStatus() == PurchaseOrderStatus.ORDERED
                    || order.getStatus() == PurchaseOrderStatus.IN_TRANSIT) {
                order.setStatus(PurchaseOrderStatus.DELAYED);
            }

            String title = "Purchase order " + order.getOrderCode() + " is delayed";
            String description = "Purchase order " + order.getOrderCode()
                    + " is " + daysLate + " day(s) overdue. Expected delivery: "
                    + order.getExpectedDeliveryDate() + ".";

            ensureRisk(
                    RiskRuleCode.DELAYED_PURCHASE_ORDER,
                    sourceRef,
                    RiskType.OPERATIONAL,
                    impact,
                    title,
                    description,
                    risk -> {
                        risk.setPurchaseOrder(order);
                        risk.setSupplier(order.getSupplier());
                    },
                    result);
        }
        resolveMissing(RiskRuleCode.DELAYED_PURCHASE_ORDER, activeRefs, result);
    }

    private void checkDelayedShipments(LocalDate today, RiskMonitoringResult result) {
        Set<String> activeRefs = new HashSet<>();
        for (Shipment shipment : shipments.findOverdueShipments(today, MONITORED_SHIPMENT_STATUSES)) {
            String sourceRef = shipment.getId().toString();
            activeRefs.add(sourceRef);
            result.delayedShipmentDetected();

            long daysLate = ChronoUnit.DAYS.between(shipment.getExpectedArrivalDate(), today);
            ImpactLevel impact = delayImpact(daysLate, shipmentHighAfterDays, shipmentCriticalAfterDays);
            if (shipment.getStatus() == ShipmentStatus.PENDING
                    || shipment.getStatus() == ShipmentStatus.SHIPPING) {
                shipment.setStatus(ShipmentStatus.DELAYED);
            }

            String title = "Shipment " + shipment.getShipmentCode() + " is delayed";
            String description = "Shipment " + shipment.getShipmentCode()
                    + " is " + daysLate + " day(s) overdue. Expected arrival: "
                    + shipment.getExpectedArrivalDate() + ".";

            ensureRisk(
                    RiskRuleCode.DELAYED_SHIPMENT,
                    sourceRef,
                    RiskType.SHIPPING,
                    impact,
                    title,
                    description,
                    risk -> {
                        risk.setShipment(shipment);
                        risk.setPurchaseOrder(shipment.getPurchaseOrder());
                        risk.setSupplier(shipment.getPurchaseOrder().getSupplier());
                    },
                    result);
        }
        resolveMissing(RiskRuleCode.DELAYED_SHIPMENT, activeRefs, result);
    }

    private void checkHighRiskSuppliers(RiskMonitoringResult result) {
        Set<String> activeRefs = new HashSet<>();
        for (Supplier supplier : suppliers.findByRiskLevel(RiskLevel.HIGH)) {
            String sourceRef = supplier.getId().toString();
            activeRefs.add(sourceRef);
            result.highRiskSupplierDetected();

            String title = "High-risk supplier detected - " + supplier.getSupplierCode();
            String description = "Supplier " + supplier.getSupplierCode()
                    + " (" + supplier.getName() + ") is currently rated HIGH risk.";

            ensureRisk(
                    RiskRuleCode.HIGH_RISK_SUPPLIER,
                    sourceRef,
                    RiskType.SUPPLIER,
                    ImpactLevel.HIGH,
                    title,
                    description,
                    risk -> risk.setSupplier(supplier),
                    result);
        }
        resolveMissing(RiskRuleCode.HIGH_RISK_SUPPLIER, activeRefs, result);
    }

    private void ensureRisk(
            RiskRuleCode ruleCode,
            String sourceRef,
            RiskType riskType,
            ImpactLevel impact,
            String title,
            String description,
            Consumer<RiskEvent> relationSetter,
            RiskMonitoringResult result) {
        RiskEvent risk = riskEvents
                .findFirstByAutoGeneratedTrueAndRuleCodeAndSourceRefAndStatusIn(
                        ruleCode, sourceRef, ACTIVE_RISK_STATUSES)
                .orElse(null);

        if (risk == null) {
            risk = new RiskEvent();
            risk.setSource(RiskEventSource.AUTOMATIC);
            risk.setAutoGenerated(true);
            risk.setRuleCode(ruleCode);
            risk.setSourceRef(sourceRef);
            risk.setStatus(RiskEventStatus.OPEN);
            risk.setDetectedAt(OffsetDateTime.now());
            risk.setRiskType(riskType);
            risk.setImpactLevel(impact);
            risk.setTitle(title);
            risk.setDescription(description);
            relationSetter.accept(risk);
            risk = riskEvents.save(risk);
            result.riskEventCreated();
            ensureAlert(risk, result);
            return;
        }

        boolean changed = risk.getRiskType() != riskType
                || risk.getImpactLevel() != impact
                || !Objects.equals(risk.getTitle(), title)
                || !Objects.equals(risk.getDescription(), description);
        relationSetter.accept(risk);
        if (changed) {
            risk.setRiskType(riskType);
            risk.setImpactLevel(impact);
            risk.setTitle(title);
            risk.setDescription(description);
            riskEvents.save(risk);
            result.riskEventUpdated();
        }
        ensureAlert(risk, result);
    }

    private void ensureAlert(RiskEvent risk, RiskMonitoringResult result) {
        Alert alert = alerts.findFirstByRiskEventIdAndStatusIn(risk.getId(), ACTIVE_ALERT_STATUSES)
                .orElse(null);
        AlertPriority priority = AlertPriority.valueOf(risk.getImpactLevel().name());

        if (alert == null) {
            alert = new Alert();
            alert.setRiskEvent(risk);
            alert.setStatus(AlertStatus.NEW);
            alert.setAlertType(risk.getRuleCode().name());
            alert.setTitle(risk.getTitle());
            alert.setMessage(risk.getDescription());
            alert.setPriority(priority);
            alerts.save(alert);
            result.alertCreated();
            return;
        }

        alert.setAlertType(risk.getRuleCode().name());
        alert.setTitle(risk.getTitle());
        alert.setMessage(risk.getDescription());
        alert.setPriority(priority);
        alerts.save(alert);
    }

    private void resolveMissing(RiskRuleCode ruleCode, Set<String> activeRefs, RiskMonitoringResult result) {
        for (RiskEvent risk : riskEvents.findByAutoGeneratedTrueAndRuleCodeAndStatusIn(
                ruleCode, ACTIVE_RISK_STATUSES)) {
            if (!activeRefs.contains(risk.getSourceRef())) {
                risk.setStatus(RiskEventStatus.RESOLVED);
                riskEvents.save(risk);
                result.riskEventResolved();
                resolveAlerts(risk, result);
            }
        }
    }

    private void resolveAlerts(RiskEvent risk, RiskMonitoringResult result) {
        OffsetDateTime resolvedAt = OffsetDateTime.now();
        for (Alert alert : alerts.findByRiskEventIdAndStatusIn(risk.getId(), ACTIVE_ALERT_STATUSES)) {
            alert.setStatus(AlertStatus.RESOLVED);
            alert.setResolvedAt(resolvedAt);
            alerts.save(alert);
            result.alertResolved();
        }
    }

    static ImpactLevel lowStockImpact(BigDecimal quantity, BigDecimal threshold) {
        if (quantity.compareTo(BigDecimal.ZERO) <= 0) {
            return ImpactLevel.CRITICAL;
        }
        if (threshold.compareTo(BigDecimal.ZERO) > 0
                && quantity.multiply(BigDecimal.valueOf(2)).compareTo(threshold) <= 0) {
            return ImpactLevel.HIGH;
        }
        return ImpactLevel.MEDIUM;
    }

    static ImpactLevel delayImpact(long daysLate, int highAfterDays, int criticalAfterDays) {
        if (daysLate > criticalAfterDays) {
            return ImpactLevel.CRITICAL;
        }
        if (daysLate >= highAfterDays) {
            return ImpactLevel.HIGH;
        }
        return ImpactLevel.MEDIUM;
    }
}
