package com.huy.enterprise.risk;

import com.huy.enterprise.common.ResourceNotFoundException;
import com.huy.enterprise.common.enums.ImpactLevel;
import com.huy.enterprise.common.enums.RiskEventSource;
import com.huy.enterprise.common.enums.RiskEventStatus;
import com.huy.enterprise.common.enums.RiskType;
import com.huy.enterprise.order.PurchaseOrderRepository;
import com.huy.enterprise.product.ProductRepository;
import com.huy.enterprise.shipment.ShipmentRepository;
import com.huy.enterprise.supplier.SupplierRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.OffsetDateTime;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class RiskEventService {
    private final RiskEventRepository repository;
    private final SupplierRepository suppliers;
    private final ProductRepository products;
    private final PurchaseOrderRepository orders;
    private final ShipmentRepository shipments;

    public List<RiskEventResponse> all() {
        return repository.findAll().stream().map(RiskEventResponse::from).toList();
    }

    public RiskEventResponse one(UUID id) {
        return RiskEventResponse.from(get(id));
    }

    @Transactional
    public RiskEventResponse create(CreateRiskEventRequest request) {
        RiskEvent event = new RiskEvent();
        event.setStatus(request.status() == null ? RiskEventStatus.OPEN : request.status());
        event.setSource(RiskEventSource.MANUAL);
        event.setAutoGenerated(false);
        event.setRuleCode(null);
        event.setSourceRef(null);
        apply(
                event,
                request.title(),
                request.riskType(),
                request.impactLevel(),
                request.description(),
                request.detectedAt() == null ? OffsetDateTime.now() : request.detectedAt(),
                request.supplierId(),
                request.productId(),
                request.purchaseOrderId(),
                request.shipmentId());
        return RiskEventResponse.from(repository.save(event));
    }

    @Transactional
    public RiskEventResponse update(UUID id, UpdateRiskEventRequest request) {
        RiskEvent event = get(id);
        apply(
                event,
                request.title(),
                request.riskType(),
                request.impactLevel(),
                request.description(),
                request.detectedAt(),
                request.supplierId(),
                request.productId(),
                request.purchaseOrderId(),
                request.shipmentId());
        return RiskEventResponse.from(repository.save(event));
    }

    @Transactional
    public RiskEventResponse status(UUID id, RiskEventStatus status) {
        RiskEvent event = get(id);
        event.setStatus(status);
        return RiskEventResponse.from(repository.save(event));
    }

    private RiskEvent get(UUID id) {
        return repository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Risk event not found: " + id));
    }

    private void apply(
            RiskEvent event,
            String title,
            RiskType type,
            ImpactLevel impact,
            String description,
            OffsetDateTime detected,
            UUID supplierId,
            UUID productId,
            UUID orderId,
            UUID shipmentId) {
        event.setTitle(title);
        event.setRiskType(type);
        event.setImpactLevel(impact);
        event.setDescription(description);
        event.setDetectedAt(detected);
        event.setSupplier(supplierId == null ? null : suppliers.findById(supplierId)
                .orElseThrow(() -> new ResourceNotFoundException("Supplier not found: " + supplierId)));
        event.setProduct(productId == null ? null : products.findById(productId)
                .orElseThrow(() -> new ResourceNotFoundException("Product not found: " + productId)));
        event.setPurchaseOrder(orderId == null ? null : orders.findById(orderId)
                .orElseThrow(() -> new ResourceNotFoundException("Purchase order not found: " + orderId)));
        event.setShipment(shipmentId == null ? null : shipments.findById(shipmentId)
                .orElseThrow(() -> new ResourceNotFoundException("Shipment not found: " + shipmentId)));
    }
}
