package com.huy.enterprise.risk;

import com.huy.enterprise.common.enums.ImpactLevel;
import com.huy.enterprise.common.enums.RiskEventSource;
import com.huy.enterprise.common.enums.RiskEventStatus;
import com.huy.enterprise.common.enums.RiskType;
import com.huy.enterprise.monitoring.RiskRuleCode;

import java.time.OffsetDateTime;
import java.util.UUID;

public record RiskEventResponse(
        UUID id,
        String title,
        RiskType riskType,
        ImpactLevel impactLevel,
        String description,
        OffsetDateTime detectedAt,
        RiskEventStatus status,
        RiskEventSource source,
        RiskRuleCode ruleCode,
        boolean autoGenerated,
        String sourceRef,
        UUID supplierId,
        UUID productId,
        UUID purchaseOrderId,
        UUID shipmentId) {

    static RiskEventResponse from(RiskEvent risk) {
        return new RiskEventResponse(
                risk.getId(),
                risk.getTitle(),
                risk.getRiskType(),
                risk.getImpactLevel(),
                risk.getDescription(),
                risk.getDetectedAt(),
                risk.getStatus(),
                risk.getSource(),
                risk.getRuleCode(),
                risk.isAutoGenerated(),
                risk.getSourceRef(),
                risk.getSupplier() == null ? null : risk.getSupplier().getId(),
                risk.getProduct() == null ? null : risk.getProduct().getId(),
                risk.getPurchaseOrder() == null ? null : risk.getPurchaseOrder().getId(),
                risk.getShipment() == null ? null : risk.getShipment().getId());
    }
}
