package com.huy.enterprise.risk;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.huy.enterprise.common.BaseEntity;
import com.huy.enterprise.common.enums.ImpactLevel;
import com.huy.enterprise.common.enums.RiskEventSource;
import com.huy.enterprise.common.enums.RiskEventStatus;
import com.huy.enterprise.common.enums.RiskType;
import com.huy.enterprise.monitoring.RiskRuleCode;
import com.huy.enterprise.order.PurchaseOrder;
import com.huy.enterprise.product.Product;
import com.huy.enterprise.shipment.Shipment;
import com.huy.enterprise.supplier.Supplier;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.OffsetDateTime;

@Getter
@Setter
@Entity
@Table(name = "risk_events")
public class RiskEvent extends BaseEntity {
    @Column(nullable = false)
    private String title;

    @Enumerated(EnumType.STRING)
    @Column(name = "risk_type", nullable = false, length = 50)
    private RiskType riskType;

    @Enumerated(EnumType.STRING)
    @Column(name = "impact_level", nullable = false, length = 30)
    private ImpactLevel impactLevel;

    private String description;

    @Column(name = "detected_at", nullable = false)
    private OffsetDateTime detectedAt;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private RiskEventStatus status = RiskEventStatus.OPEN;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private RiskEventSource source = RiskEventSource.MANUAL;

    @Enumerated(EnumType.STRING)
    @Column(name = "rule_code", length = 50)
    private RiskRuleCode ruleCode;

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = false;

    @Column(name = "source_ref", length = 100)
    private String sourceRef;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplier_id")
    private Supplier supplier;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private Product product;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "purchase_order_id")
    private PurchaseOrder purchaseOrder;

    @JsonIgnore
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shipment_id")
    private Shipment shipment;
}
