package com.huy.enterprise.risk;

import com.huy.enterprise.common.enums.ImpactLevel;
import com.huy.enterprise.common.enums.RiskEventStatus;
import com.huy.enterprise.monitoring.RiskRuleCode;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.Collection;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public interface RiskEventRepository extends JpaRepository<RiskEvent, UUID> {
    long countByStatus(RiskEventStatus status);

    Optional<RiskEvent> findFirstByAutoGeneratedTrueAndRuleCodeAndSourceRefAndStatusIn(
            RiskRuleCode ruleCode,
            String sourceRef,
            Collection<RiskEventStatus> statuses);

    List<RiskEvent> findByAutoGeneratedTrueAndRuleCodeAndStatusIn(
            RiskRuleCode ruleCode,
            Collection<RiskEventStatus> statuses);

    List<RiskEvent> findByAutoGeneratedTrueAndStatusIn(Collection<RiskEventStatus> statuses);

    long countByAutoGeneratedTrueAndStatusIn(Collection<RiskEventStatus> statuses);

    long countByAutoGeneratedTrueAndImpactLevelAndStatusIn(
            ImpactLevel impactLevel,
            Collection<RiskEventStatus> statuses);
}
