import { useEffect,useMemo,useState } from 'react'
import { Link } from 'react-router-dom'
import { alertApi } from '../api/alertApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import Badge from '../components/Badge'
import { EmptyState,ErrorState,LoadingState } from '../components/States'
const weight={CRITICAL:4,HIGH:3,MEDIUM:2,LOW:1}
export default function AlertPage(){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=async()=>{setLoading(true);try{setRows(await alertApi.getAll());setError('')}catch(e){setError(getApiErrorMessage(e,'Không thể tải cảnh báo.'))}finally{setLoading(false)}};useEffect(()=>{load()},[]);const sorted=useMemo(()=>[...rows].sort((a,b)=>(a.status==='RESOLVED')-(b.status==='RESOLVED')||(weight[b.priority]-weight[a.priority])),[rows]);const setStatus=async(item,status)=>{if(!window.confirm(`Chuyển cảnh báo "${item.title}" sang ${status}?`))return;try{await alertApi.updateStatus(item.id,status);await load()}catch(e){window.alert(getApiErrorMessage(e))}};return <><PageHeader title="Cảnh báo" description="Các cảnh báo nghiệp vụ cần đọc hoặc xử lý." actions={<Link className="btn btn-primary" to="/alerts/new">+ Tạo cảnh báo</Link>}/>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:sorted.length===0?<EmptyState title="Chưa có cảnh báo nào."/>:<div className="panel table-wrap"><table><thead><tr><th>Tiêu đề</th><th>Loại</th><th>Mức ưu tiên</th><th>Trạng thái</th><th>Nội dung</th><th></th></tr></thead><tbody>{sorted.map(r=><tr key={r.id}><td className="strong">{r.title}</td><td>{r.alertType}</td><td><Badge value={r.priority}/></td><td><Badge value={r.status}/></td><td>{r.message}</td><td className="row-actions">{r.status==='NEW'&&<button className="link-button" onClick={()=>setStatus(r,'READ')}>Đã đọc</button>}{r.status!=='RESOLVED'&&<button className="link-button success" onClick={()=>setStatus(r,'RESOLVED')}>Xử lý</button>}{r.riskEventId&&<Link to={`/risks/${r.riskEventId}`}>Rủi ro</Link>}</td></tr>)}</tbody></table></div>}</>}
