import { useEffect,useState } from 'react'
import { Link,useNavigate } from 'react-router-dom'
import { alertApi } from '../api/alertApi'
import { riskEventApi } from '../api/riskEventApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import FormField from '../components/FormField'
import { LoadingState } from '../components/States'
const initial={title:'',message:'',alertType:'RISK',priority:'MEDIUM',riskEventId:''}
export default function AlertFormPage(){const navigate=useNavigate();const[form,setForm]=useState(initial),[risks,setRisks]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{riskEventApi.getAll().then(setRisks).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false))},[]);const set=k=>e=>setForm(p=>({...p,[k]:e.target.value}));const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{await alertApi.create({title:form.title.trim(),message:form.message.trim(),alertType:form.alertType.trim(),priority:form.priority,recipientUserId:null,riskEventId:form.riskEventId||null});navigate('/alerts')}catch(e2){setError(getApiErrorMessage(e2,'Không thể tạo cảnh báo.'))}finally{setSaving(false)}};if(loading)return <LoadingState/>;return <><PageHeader title="Tạo cảnh báo" description="Giai đoạn 3 chưa có authentication nên recipientUserId để trống."/><form className="panel form-panel" onSubmit={submit}>{error&&<div className="alert alert-danger">{error}</div>}<div className="form-grid"><FormField label="Tiêu đề" required><input value={form.title} onChange={set('title')} required/></FormField><FormField label="Loại cảnh báo" required><input value={form.alertType} onChange={set('alertType')} placeholder="RISK, INVENTORY, SHIPPING..." required/></FormField><FormField label="Mức ưu tiên"><select value={form.priority} onChange={set('priority')}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></FormField><FormField label="Sự kiện rủi ro"><select value={form.riskEventId} onChange={set('riskEventId')}><option value="">Không liên kết</option>{risks.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></FormField><FormField label="Nội dung" required><textarea rows="5" value={form.message} onChange={set('message')} required/></FormField></div><div className="form-actions"><Link className="btn btn-secondary" to="/alerts">Hủy</Link><button className="btn btn-primary" disabled={saving}>{saving?'Đang lưu...':'Tạo cảnh báo'}</button></div></form></>}
