import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { categoryApi } from '../api/categoryApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import Badge from '../components/Badge'
import { EmptyState,ErrorState,LoadingState } from '../components/States'
const emptyForm={name:'',code:'',description:'',status:'ACTIVE'}
export default function CategoryPage(){const[rows,setRows]=useState([]),[form,setForm]=useState(emptyForm),[editingId,setEditingId]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=async()=>{setLoading(true);try{setRows(await categoryApi.getAll());setError('')}catch(e){setError(getApiErrorMessage(e))}finally{setLoading(false)}};useEffect(()=>{load()},[]);const submit=async e=>{e.preventDefault();try{editingId?await categoryApi.update(editingId,form):await categoryApi.create(form);setEditingId(null);setForm(emptyForm);await load()}catch(e2){window.alert(getApiErrorMessage(e2,'Không thể lưu danh mục.'))}};const edit=item=>{setEditingId(item.id);setForm({name:item.name,code:item.code,description:item.description||'',status:item.status})};return <><PageHeader title="Danh mục sản phẩm" description="Quản lý nhóm sản phẩm dùng cho dropdown tạo sản phẩm." actions={<Link className="btn btn-secondary" to="/products">← Sản phẩm</Link>}/><div className="split-grid"><form className="panel form-panel" onSubmit={submit}><h2>{editingId?'Cập nhật danh mục':'Thêm danh mục'}</h2><label className="form-field"><span className="form-label">Mã danh mục *</span><input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} required/></label><label className="form-field"><span className="form-label">Tên *</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label className="form-field"><span className="form-label">Mô tả</span><textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="form-field"><span className="form-label">Trạng thái</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>ACTIVE</option><option>INACTIVE</option></select></label><div className="form-actions">{editingId&&<button type="button" className="btn btn-secondary" onClick={()=>{setEditingId(null);setForm(emptyForm)}}>Hủy sửa</button>}<button className="btn btn-primary">{editingId?'Cập nhật':'Thêm danh mục'}</button></div></form><div>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:rows.length===0?<EmptyState/>:<div className="panel table-wrap"><table><thead><tr><th>Mã</th><th>Tên</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td className="mono">{r.code}</td><td>{r.name}</td><td><Badge value={r.status}/></td><td><button className="link-button" onClick={()=>edit(r)}>Sửa</button></td></tr>)}</tbody></table></div>}</div></div></>}
