import { useEffect,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { inventoryApi } from '../api/inventoryApi'
import { warehouseApi } from '../api/warehouseApi'
import { productApi } from '../api/productApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import FormField from '../components/FormField'
import { LoadingState } from '../components/States'
const initial={warehouseId:'',productId:'',quantity:0,lowStockThreshold:0}
export default function InventoryFormPage(){const{id}=useParams(),editing=Boolean(id),navigate=useNavigate();const[form,setForm]=useState(initial),[warehouses,setWarehouses]=useState([]),[products,setProducts]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{Promise.all([warehouseApi.getAll(),productApi.getAll(),editing?inventoryApi.getById(id):Promise.resolve(null)]).then(([w,p,item])=>{setWarehouses(w);setProducts(p);if(item)setForm({warehouseId:item.warehouseId,productId:item.productId,quantity:item.quantity,lowStockThreshold:item.lowStockThreshold})}).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false))},[editing,id]);const set=k=>e=>setForm(p=>({...p,[k]:e.target.value}));const submit=async e=>{e.preventDefault();setSaving(true);setError('');const payload={warehouseId:form.warehouseId,productId:form.productId,quantity:Number(form.quantity),lowStockThreshold:Number(form.lowStockThreshold)};try{editing?await inventoryApi.update(id,payload):await inventoryApi.create(payload);navigate('/inventory')}catch(e2){setError(getApiErrorMessage(e2,'Không thể lưu tồn kho.'))}finally{setSaving(false)}};if(loading)return <LoadingState/>;return <><PageHeader title={editing?'Cập nhật tồn kho':'Thêm tồn kho'}/><form className="panel form-panel" onSubmit={submit}>{error&&<div className="alert alert-danger">{error}</div>}<div className="form-grid"><FormField label="Kho" required><select value={form.warehouseId} onChange={set('warehouseId')} required><option value="">Chọn kho</option>{warehouses.filter(x=>x.status!=='INACTIVE').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><FormField label="Sản phẩm" required><select value={form.productId} onChange={set('productId')} required><option value="">Chọn sản phẩm</option>{products.filter(x=>x.status!=='INACTIVE').map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></FormField><FormField label="Số lượng" required><input type="number" min="0" step="0.01" value={form.quantity} onChange={set('quantity')} required/></FormField><FormField label="Ngưỡng sắp hết" required><input type="number" min="0" step="0.01" value={form.lowStockThreshold} onChange={set('lowStockThreshold')} required/></FormField></div><div className="form-actions"><Link className="btn btn-secondary" to="/inventory">Hủy</Link><button className="btn btn-primary" disabled={saving}>{saving?'Đang lưu...':'Lưu tồn kho'}</button></div></form></>}
