import { useEffect,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { productApi } from '../api/productApi'
import { categoryApi } from '../api/categoryApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import FormField from '../components/FormField'
import { LoadingState } from '../components/States'
const initial={productCode:'',name:'',categoryId:'',unit:'',referencePrice:'',description:'',status:'ACTIVE'}
export default function ProductFormPage(){const{id}=useParams(),editing=Boolean(id),navigate=useNavigate();const[form,setForm]=useState(initial),[categories,setCategories]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{Promise.all([categoryApi.getAll(),editing?productApi.getById(id):Promise.resolve(null)]).then(([cats,product])=>{setCategories(cats);if(product)setForm({...initial,...product,categoryId:product.categoryId||'',referencePrice:product.referencePrice??''})}).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false))},[editing,id]);const set=key=>e=>setForm(p=>({...p,[key]:e.target.value}));const submit=async e=>{e.preventDefault();setSaving(true);setError('');const common={categoryId:form.categoryId||null,name:form.name.trim(),unit:form.unit.trim(),referencePrice:form.referencePrice===''?null:Number(form.referencePrice),description:form.description||null,status:form.status};try{editing?await productApi.update(id,common):await productApi.create({productCode:form.productCode.trim(),...common});navigate('/products')}catch(e2){setError(getApiErrorMessage(e2,'Không thể lưu sản phẩm.'))}finally{setSaving(false)}};if(loading)return <LoadingState/>;return <><PageHeader title={editing?'Cập nhật sản phẩm':'Thêm sản phẩm'} description="Danh mục được lấy trực tiếp từ backend."/><form className="panel form-panel" onSubmit={submit}>{error&&<div className="alert alert-danger">{error}</div>}<div className="form-grid"><FormField label="Mã sản phẩm" required><input value={form.productCode} onChange={set('productCode')} disabled={editing} required={!editing}/></FormField><FormField label="Tên sản phẩm" required><input value={form.name} onChange={set('name')} required/></FormField><FormField label="Danh mục"><select value={form.categoryId} onChange={set('categoryId')}><option value="">Chưa phân loại</option>{categories.filter(c=>c.status!=='INACTIVE').map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></FormField><FormField label="Đơn vị" required><input value={form.unit} onChange={set('unit')} placeholder="cái, kg, thùng..." required/></FormField><FormField label="Giá tham chiếu"><input type="number" min="0" step="0.01" value={form.referencePrice} onChange={set('referencePrice')}/></FormField><FormField label="Trạng thái"><select value={form.status} onChange={set('status')}><option>ACTIVE</option><option>INACTIVE</option></select></FormField><FormField label="Mô tả"><textarea rows="4" value={form.description} onChange={set('description')}/></FormField></div><div className="form-actions"><Link className="btn btn-secondary" to="/products">Hủy</Link><button className="btn btn-primary" disabled={saving}>{saving?'Đang lưu...':'Lưu sản phẩm'}</button></div></form></>}
