import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { productApi } from '../api/productApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import Badge from '../components/Badge'
import { EmptyState,ErrorState,LoadingState } from '../components/States'
import { formatCurrency } from '../utils/formatters'
export default function ProductListPage(){const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=async()=>{setLoading(true);try{setRows(await productApi.getAll());setError('')}catch(e){setError(getApiErrorMessage(e,'Không thể tải sản phẩm.'))}finally{setLoading(false)}};useEffect(()=>{load()},[]);const deactivate=async item=>{if(!window.confirm(`Ngừng hoạt động sản phẩm "${item.name}"?`))return;try{await productApi.deactivate(item.id);await load()}catch(e){window.alert(getApiErrorMessage(e))}};return <><PageHeader title="Sản phẩm" description="Danh mục hàng hóa dùng trong tồn kho và đơn mua hàng." actions={<div className="button-row"><Link className="btn btn-secondary" to="/product-categories">Danh mục</Link><Link className="btn btn-primary" to="/products/new">+ Thêm sản phẩm</Link></div>}/>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:rows.length===0?<EmptyState title="Chưa có sản phẩm nào."/>:<div className="panel table-wrap"><table><thead><tr><th>Mã SP</th><th>Tên</th><th>Danh mục</th><th>Đơn vị</th><th>Giá tham chiếu</th><th>Trạng thái</th><th></th></tr></thead><tbody>{rows.map(item=><tr key={item.id}><td className="mono">{item.productCode}</td><td>{item.name}</td><td>{item.categoryName||'—'}</td><td>{item.unit}</td><td>{formatCurrency(item.referencePrice)}</td><td><Badge value={item.status}/></td><td className="row-actions"><Link to={`/products/${item.id}/edit`}>Sửa</Link>{item.status!=='INACTIVE'&&<button className="link-button danger" onClick={()=>deactivate(item)}>Ngừng</button>}</td></tr>)}</tbody></table></div>}</>}
