import { useEffect,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { purchaseOrderApi } from '../api/purchaseOrderApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import Badge from '../components/Badge'
import { ErrorState,LoadingState } from '../components/States'
import { formatCurrency,formatDate } from '../utils/formatters'
const statuses=['DRAFT','ORDERED','IN_TRANSIT','DELIVERED','CANCELLED','DELAYED']
export default function PurchaseOrderDetailPage(){const{id}=useParams();const[item,setItem]=useState(null),[error,setError]=useState(''),[changing,setChanging]=useState(false);const load=async()=>{try{setItem(await purchaseOrderApi.getById(id));setError('')}catch(e){setError(getApiErrorMessage(e))}};useEffect(()=>{load()},[id]);const changeStatus=async status=>{if(status===item.status)return;if(!window.confirm(`Đổi trạng thái đơn sang ${status}?`))return;setChanging(true);try{setItem(await purchaseOrderApi.updateStatus(id,status))}catch(e){window.alert(getApiErrorMessage(e))}finally{setChanging(false)}};if(error)return <ErrorState message={error} onRetry={load}/>;if(!item)return <LoadingState/>;return <><PageHeader title={item.orderCode} description={`Đơn mua hàng · ${item.supplierName}`} actions={<Link className="btn btn-primary" to={`/purchase-orders/${id}/edit`}>Chỉnh sửa</Link>}/><div className="panel detail-grid"><div><small>Nhà cung cấp</small><strong>{item.supplierName}</strong></div><div><small>Trạng thái</small><Badge value={item.status}/></div><div><small>Ngày đặt</small><strong>{formatDate(item.orderDate)}</strong></div><div><small>Giao dự kiến</small><strong>{formatDate(item.expectedDeliveryDate)}</strong></div><div><small>Tổng tiền</small><strong>{formatCurrency(item.totalAmount)}</strong></div><div><small>Đổi trạng thái</small><select value={item.status} disabled={changing} onChange={e=>changeStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="detail-span"><small>Ghi chú</small><strong>{item.notes||'—'}</strong></div></div><div className="panel table-wrap"><table><thead><tr><th>Sản phẩm</th><th>Số lượng</th><th>Đơn giá</th><th>Thành tiền</th></tr></thead><tbody>{item.items.map(r=><tr key={r.id}><td>{r.productName}</td><td>{r.quantity}</td><td>{formatCurrency(r.unitPrice)}</td><td className="strong">{formatCurrency(r.lineTotal)}</td></tr>)}</tbody><tfoot><tr><td colSpan="3">TOTAL</td><td>{formatCurrency(item.totalAmount)}</td></tr></tfoot></table></div></>}
