import { useEffect,useState } from 'react'
import { Link,useParams } from 'react-router-dom'
import { riskEventApi } from '../api/riskEventApi'
import { supplierApi } from '../api/supplierApi'
import { productApi } from '../api/productApi'
import { purchaseOrderApi } from '../api/purchaseOrderApi'
import { shipmentApi } from '../api/shipmentApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import Badge from '../components/Badge'
import { ErrorState,LoadingState } from '../components/States'
import { formatDateTime } from '../utils/formatters'
const statuses=['OPEN','INVESTIGATING','RESOLVED','CLOSED']
export default function RiskDetailPage(){const{id}=useParams();const[item,setItem]=useState(null),[names,setNames]=useState({}),[error,setError]=useState('');const load=async()=>{try{const[risk,suppliers,products,orders,shipments]=await Promise.all([riskEventApi.getById(id),supplierApi.getAll(),productApi.getAll(),purchaseOrderApi.getAll(),shipmentApi.getAll()]);setItem(risk);setNames({supplier:suppliers.find(x=>x.id===risk.supplierId),product:products.find(x=>x.id===risk.productId),order:orders.find(x=>x.id===risk.purchaseOrderId),shipment:shipments.find(x=>x.id===risk.shipmentId)});setError('')}catch(e){setError(getApiErrorMessage(e))}};useEffect(()=>{load()},[id]);const change=async status=>{if(status===item.status)return;if(!window.confirm(`Đổi trạng thái rủi ro sang ${status}?`))return;try{setItem(await riskEventApi.updateStatus(id,status))}catch(e){window.alert(getApiErrorMessage(e))}};if(error)return <ErrorState message={error} onRetry={load}/>;if(!item)return <LoadingState/>;return <><PageHeader title={item.title} description={`${item.riskType} · ${formatDateTime(item.detectedAt)}`} actions={<Link className="btn btn-primary" to={`/risks/${id}/edit`}>Chỉnh sửa</Link>}/><div className="panel detail-grid"><div><small>Loại rủi ro</small><strong>{item.riskType}</strong></div><div><small>Mức ảnh hưởng</small><Badge value={item.impactLevel}/></div><div><small>Trạng thái</small><Badge value={item.status}/></div><div><small>Đổi trạng thái</small><select value={item.status} onChange={e=>change(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div><small>Nhà cung cấp</small>{item.supplierId?<Link className="table-link" to={`/suppliers/${item.supplierId}`}>{names.supplier?.name||item.supplierId}</Link>:<strong>—</strong>}</div><div><small>Sản phẩm</small><strong>{names.product?.name||(item.productId?'Đã liên kết':'—')}</strong></div><div><small>Đơn mua hàng</small>{item.purchaseOrderId?<Link className="table-link" to={`/purchase-orders/${item.purchaseOrderId}`}>{names.order?.orderCode||item.purchaseOrderId}</Link>:<strong>—</strong>}</div><div><small>Vận chuyển</small>{item.shipmentId?<Link className="table-link" to={`/shipments/${item.shipmentId}`}>{names.shipment?.shipmentCode||item.shipmentId}</Link>:<strong>—</strong>}</div><div className="detail-span"><small>Mô tả</small><strong>{item.description||'—'}</strong></div></div></>}
