import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { riskEventApi } from '../api/riskEventApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import Badge from '../components/Badge'
import { EmptyState, ErrorState, LoadingState } from '../components/States'
import { formatDateTime } from '../utils/formatters'

const weight = { CRITICAL: 4, HIGH: 3, MEDIUM: 2, LOW: 1 }

export default function RiskListPage() {
  const [rows, setRows] = useState([])
  const [sourceFilter, setSourceFilter] = useState('ALL')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const load = async () => {
    setLoading(true)
    try {
      setRows(await riskEventApi.getAll())
      setError('')
    } catch (e) {
      setError(getApiErrorMessage(e, 'Không thể tải sự kiện rủi ro.'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { load() }, [])

  const sorted = useMemo(() => rows
    .filter((row) => sourceFilter === 'ALL' || row.source === sourceFilter)
    .sort((a, b) => (weight[b.impactLevel] - weight[a.impactLevel]) || (new Date(b.detectedAt) - new Date(a.detectedAt))), [rows, sourceFilter])

  return <>
    <PageHeader title="Sự kiện rủi ro" description="Theo dõi rủi ro thủ công và các rủi ro do Risk Monitoring Engine tự động phát hiện." actions={<div className="row-actions">
      <select value={sourceFilter} onChange={(e) => setSourceFilter(e.target.value)} aria-label="Lọc nguồn rủi ro">
        <option value="ALL">Tất cả nguồn</option>
        <option value="MANUAL">Thủ công</option>
        <option value="AUTOMATIC">Tự động</option>
      </select>
      <Link className="btn btn-primary" to="/risks/new">+ Ghi nhận rủi ro</Link>
    </div>} />
    {loading ? <LoadingState /> : error ? <ErrorState message={error} onRetry={load} /> : sorted.length === 0 ? <EmptyState title="Không có sự kiện rủi ro phù hợp bộ lọc." /> : <div className="panel table-wrap">
      <table>
        <thead><tr><th>Tiêu đề</th><th>Nguồn</th><th>Rule</th><th>Loại</th><th>Mức ảnh hưởng</th><th>Phát hiện</th><th>Trạng thái</th><th>Liên quan</th><th></th></tr></thead>
        <tbody>{sorted.map((risk) => {
          const related = risk.supplierId ? 'Supplier' : risk.productId ? 'Product' : risk.purchaseOrderId ? 'Purchase Order' : risk.shipmentId ? 'Shipment' : '—'
          return <tr key={risk.id}>
            <td><Link className="table-link" to={`/risks/${risk.id}`}>{risk.title}</Link></td>
            <td><Badge value={risk.source || (risk.autoGenerated ? 'AUTOMATIC' : 'MANUAL')} /></td>
            <td>{risk.ruleCode || '—'}</td>
            <td>{risk.riskType}</td>
            <td><Badge value={risk.impactLevel} /></td>
            <td>{formatDateTime(risk.detectedAt)}</td>
            <td><Badge value={risk.status} /></td>
            <td>{related}</td>
            <td className="row-actions"><Link to={`/risks/${risk.id}`}>Xem</Link>{!risk.autoGenerated && <Link to={`/risks/${risk.id}/edit`}>Sửa</Link>}</td>
          </tr>
        })}</tbody>
      </table>
    </div>}
  </>
}
