import { useEffect,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { supplierApi } from '../api/supplierApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import FormField from '../components/FormField'
import { LoadingState } from '../components/States'
const initial={supplierCode:'',name:'',email:'',phone:'',address:'',country:'',region:'',status:'ACTIVE',riskLevel:'LOW',notes:''}
export default function SupplierFormPage(){const{id}=useParams(),editing=Boolean(id),navigate=useNavigate();const[form,setForm]=useState(initial),[loading,setLoading]=useState(editing),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{if(!editing)return;supplierApi.getById(id).then(data=>setForm({...initial,...data})).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false))},[editing,id]);const set=key=>e=>setForm(prev=>({...prev,[key]:e.target.value}));const submit=async e=>{e.preventDefault();setSaving(true);setError('');const common={name:form.name.trim(),email:form.email||null,phone:form.phone||null,address:form.address||null,country:form.country||null,region:form.region||null,status:form.status,riskLevel:form.riskLevel,notes:form.notes||null};try{const saved=editing?await supplierApi.update(id,common):await supplierApi.create({supplierCode:form.supplierCode.trim(),...common});navigate(`/suppliers/${saved.id}`)}catch(e2){setError(getApiErrorMessage(e2,'Không thể lưu nhà cung cấp.'))}finally{setSaving(false)}};if(loading)return <LoadingState/>;return <><PageHeader title={editing?'Cập nhật nhà cung cấp':'Thêm nhà cung cấp'} description="Thông tin này được lưu trực tiếp qua REST API Spring Boot."/><form className="panel form-panel" onSubmit={submit}>{error&&<div className="alert alert-danger">{error}</div>}<div className="form-grid"><FormField label="Mã nhà cung cấp" required><input value={form.supplierCode} onChange={set('supplierCode')} disabled={editing} required={!editing}/></FormField><FormField label="Tên nhà cung cấp" required><input value={form.name} onChange={set('name')} required/></FormField><FormField label="Email"><input type="email" value={form.email} onChange={set('email')}/></FormField><FormField label="Điện thoại"><input value={form.phone} onChange={set('phone')}/></FormField><FormField label="Quốc gia"><input value={form.country} onChange={set('country')}/></FormField><FormField label="Khu vực"><input value={form.region} onChange={set('region')}/></FormField><FormField label="Mức rủi ro"><select value={form.riskLevel} onChange={set('riskLevel')}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></FormField><FormField label="Trạng thái"><select value={form.status} onChange={set('status')}><option>ACTIVE</option><option>INACTIVE</option></select></FormField><FormField label="Địa chỉ"><textarea value={form.address} onChange={set('address')} rows="3"/></FormField><FormField label="Ghi chú"><textarea value={form.notes} onChange={set('notes')} rows="3"/></FormField></div><div className="form-actions"><Link className="btn btn-secondary" to={editing?`/suppliers/${id}`:'/suppliers'}>Hủy</Link><button className="btn btn-primary" disabled={saving}>{saving?'Đang lưu...':'Lưu nhà cung cấp'}</button></div></form></>}
