import { useEffect,useState } from 'react'
import { Link,useNavigate,useParams } from 'react-router-dom'
import { warehouseApi } from '../api/warehouseApi'
import { getApiErrorMessage } from '../api/apiClient'
import PageHeader from '../components/PageHeader'
import FormField from '../components/FormField'
import { LoadingState } from '../components/States'
const initial={warehouseCode:'',name:'',address:'',status:'ACTIVE'}
export default function WarehouseFormPage(){const{id}=useParams(),editing=Boolean(id),navigate=useNavigate();const[form,setForm]=useState(initial),[loading,setLoading]=useState(editing),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>{if(!editing)return;warehouseApi.getById(id).then(setForm).catch(e=>setError(getApiErrorMessage(e))).finally(()=>setLoading(false))},[editing,id]);const set=k=>e=>setForm(p=>({...p,[k]:e.target.value}));const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{editing?await warehouseApi.update(id,form):await warehouseApi.create(form);navigate('/warehouses')}catch(e2){setError(getApiErrorMessage(e2,'Không thể lưu kho.'))}finally{setSaving(false)}};if(loading)return <LoadingState/>;return <><PageHeader title={editing?'Cập nhật kho':'Thêm kho'}/><form className="panel form-panel" onSubmit={submit}>{error&&<div className="alert alert-danger">{error}</div>}<div className="form-grid"><FormField label="Mã kho" required><input value={form.warehouseCode} onChange={set('warehouseCode')} required/></FormField><FormField label="Tên kho" required><input value={form.name} onChange={set('name')} required/></FormField><FormField label="Trạng thái"><select value={form.status} onChange={set('status')}><option>ACTIVE</option><option>INACTIVE</option></select></FormField><FormField label="Địa chỉ"><textarea rows="3" value={form.address||''} onChange={set('address')}/></FormField></div><div className="form-actions"><Link className="btn btn-secondary" to="/warehouses">Hủy</Link><button className="btn btn-primary" disabled={saving}>{saving?'Đang lưu...':'Lưu kho'}</button></div></form></>}
