server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: enterprise-risk-backend
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/${DB_NAME:enterprise_risk_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
