package com.huy.enterprise;

import com.huy.enterprise.alert.AlertRepository;
import com.huy.enterprise.common.enums.AlertStatus;
import com.huy.enterprise.common.enums.ImpactLevel;
import com.huy.enterprise.common.enums.PurchaseOrderStatus;
import com.huy.enterprise.common.enums.RiskEventSource;
import com.huy.enterprise.common.enums.RiskEventStatus;
import com.huy.enterprise.common.enums.RiskLevel;
import com.huy.enterprise.common.enums.RiskType;
import com.huy.enterprise.common.enums.ShipmentStatus;
import com.huy.enterprise.inventory.InventoryItem;
import com.huy.enterprise.inventory.InventoryItemRepository;
import com.huy.enterprise.inventory.Warehouse;
import com.huy.enterprise.inventory.WarehouseRepository;
import com.huy.enterprise.monitoring.RiskMonitoringResult;
import com.huy.enterprise.monitoring.RiskMonitoringService;
import com.huy.enterprise.order.PurchaseOrder;
import com.huy.enterprise.order.PurchaseOrderRepository;
import com.huy.enterprise.product.Product;
import com.huy.enterprise.product.ProductRepository;
import com.huy.enterprise.risk.RiskEvent;
import com.huy.enterprise.risk.RiskEventRepository;
import com.huy.enterprise.shipment.Shipment;
import com.huy.enterprise.shipment.ShipmentRepository;
import com.huy.enterprise.supplier.Supplier;
import com.huy.enterprise.supplier.SupplierRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@Transactional
class Phase5RiskMonitoringIntegrationTests {
    @Autowired RiskMonitoringService monitoring;
    @Autowired SupplierRepository suppliers;
    @Autowired ProductRepository products;
    @Autowired WarehouseRepository warehouses;
    @Autowired InventoryItemRepository inventory;
    @Autowired PurchaseOrderRepository orders;
    @Autowired ShipmentRepository shipments;
    @Autowired RiskEventRepository risks;
    @Autowired AlertRepository alerts;

    @Test
    void fullMonitoringCycleDetectsDeduplicatesAndAutoResolvesWithoutTouchingManualRisk() {
        LocalDate today = LocalDate.now();

        Supplier supplier = new Supplier();
        supplier.setSupplierCode("SUP-P5");
        supplier.setName("Phase 5 Supplier");
        supplier.setRiskLevel(RiskLevel.HIGH);
        supplier = suppliers.save(supplier);

        Product product = new Product();
        product.setProductCode("PROD-P5");
        product.setName("Phase 5 Product");
        product.setUnit("pcs");
        product = products.save(product);

        Warehouse warehouse = new Warehouse();
        warehouse.setWarehouseCode("WH-P5");
        warehouse.setName("Phase 5 Warehouse");
        warehouse = warehouses.save(warehouse);

        InventoryItem item = new InventoryItem();
        item.setWarehouse(warehouse);
        item.setProduct(product);
        item.setQuantity(new BigDecimal("5"));
        item.setLowStockThreshold(new BigDecimal("20"));
        item = inventory.save(item);

        PurchaseOrder order = new PurchaseOrder();
        order.setOrderCode("PO-P5");
        order.setSupplier(supplier);
        order.setOrderDate(today.minusDays(10));
        order.setExpectedDeliveryDate(today.minusDays(4));
        order.setStatus(PurchaseOrderStatus.ORDERED);
        order = orders.save(order);

        Shipment shipment = new Shipment();
        shipment.setShipmentCode("SHIP-P5");
        shipment.setPurchaseOrder(order);
        shipment.setExpectedArrivalDate(today.minusDays(4));
        shipment.setStatus(ShipmentStatus.SHIPPING);
        shipment = shipments.save(shipment);

        RiskEvent manualRisk = new RiskEvent();
        manualRisk.setTitle("Manual risk must remain untouched");
        manualRisk.setRiskType(RiskType.OPERATIONAL);
        manualRisk.setImpactLevel(ImpactLevel.MEDIUM);
        manualRisk.setDescription("Created by analyst, not by monitoring engine.");
        manualRisk.setDetectedAt(OffsetDateTime.now());
        manualRisk.setStatus(RiskEventStatus.OPEN);
        manualRisk.setSource(RiskEventSource.MANUAL);
        manualRisk.setAutoGenerated(false);
        manualRisk = risks.save(manualRisk);

        RiskMonitoringResult first = monitoring.runMonitoring();

        assertThat(first.getLowStockDetected()).isEqualTo(1);
        assertThat(first.getDelayedPurchaseOrders()).isEqualTo(1);
        assertThat(first.getDelayedShipments()).isEqualTo(1);
        assertThat(first.getHighRiskSuppliers()).isEqualTo(1);
        assertThat(first.getRiskEventsCreated()).isEqualTo(4);
        assertThat(first.getAlertsCreated()).isEqualTo(4);
        assertThat(orders.findById(order.getId()).orElseThrow().getStatus()).isEqualTo(PurchaseOrderStatus.DELAYED);
        assertThat(shipments.findById(shipment.getId()).orElseThrow().getStatus()).isEqualTo(ShipmentStatus.DELAYED);
        assertThat(risks.findAll()).hasSize(5);
        assertThat(alerts.findAll()).hasSize(4);

        RiskMonitoringResult second = monitoring.runMonitoring();

        assertThat(second.getRiskEventsCreated()).isZero();
        assertThat(second.getAlertsCreated()).isZero();
        assertThat(risks.findAll()).hasSize(5);
        assertThat(alerts.findAll()).hasSize(4);

        item.setQuantity(new BigDecimal("100"));
        inventory.save(item);
        supplier.setRiskLevel(RiskLevel.MEDIUM);
        suppliers.save(supplier);
        order.setStatus(PurchaseOrderStatus.DELIVERED);
        orders.save(order);
        shipment.setStatus(ShipmentStatus.ARRIVED);
        shipments.save(shipment);

        RiskMonitoringResult cleared = monitoring.runMonitoring();

        assertThat(cleared.getRiskEventsResolved()).isEqualTo(4);
        assertThat(cleared.getAlertsResolved()).isEqualTo(4);
        assertThat(risks.findById(manualRisk.getId()).orElseThrow().getStatus()).isEqualTo(RiskEventStatus.OPEN);
        assertThat(risks.findById(manualRisk.getId()).orElseThrow().isAutoGenerated()).isFalse();
        assertThat(risks.findAll().stream().filter(RiskEvent::isAutoGenerated))
                .allMatch(risk -> risk.getStatus() == RiskEventStatus.RESOLVED);
        assertThat(alerts.findAll())
                .allMatch(alert -> alert.getStatus() == AlertStatus.RESOLVED && alert.getResolvedAt() != null);
    }
}
